services:
  database:
    image: postgres:15-alpine
    container_name: ${DB_CONTAINER_NAME}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_CONTAINER_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    environment:
      POSTGRES_DB: ${DB_CONTAINER_NAME}
      POSTGRES_USER: ${DB_USERNAME} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    expose:
      - ${DB_PORT}
    networks:
      - ${NETWORK_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ../..
      dockerfile: ./deploy/prod/backend/Dockerfile
    container_name: ${BACKEND_CONTAINER_NAME}
    environment:
      DB_HOST: ${DB_HOST}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    expose:
      - ${BACKEND_PORT}
    networks:
      - ${NETWORK_NAME}
    depends_on:
      database:
        condition: service_healthy

  nginx:
    build:
      context: ../..
      dockerfile: ./deploy/prod/frontend/Dockerfile
    container_name: ${NGINX_CONTAINER_NAME}
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - ${NETWORK_NAME}
    depends_on:
      backend:
        condition: service_started

networks:
  dummy-network:
    driver: bridge

volumes:
  postgres_data:
